#!/bin/bash
# Test script for CV Builder AI Generation feature

echo "==================================="
echo "CV Builder AI Generation Test Plan"
echo "==================================="
echo ""
echo "This script documents how to test the new CV Builder AI generation feature."
echo ""
echo "Prerequisites:"
echo "1. Backend server running (python manage.py runserver)"
echo "2. Frontend server running (npm run dev)"
echo "3. User logged in"
echo "4. GROQ_API_KEY configured in backend .env"
echo ""
echo "Test Steps:"
echo ""
echo "1. Navigate to CV Builder"
echo "   - Go to /cv-master in the application"
echo "   - Verify the CV Builder form loads"
echo ""
echo "2. Click 'AI Generate' button"
echo "   - Look for the button with sparkles icon"
echo "   - Click it and wait for generation"
echo "   - Button should show 'Generating...' with spinner"
echo ""
echo "3. Verify AI Content Populates Form"
echo "   - Personal information fields should fill"
echo "   - Professional summary should appear"
echo "   - Experience entries should be added"
echo "   - Skills should be populated"
echo "   - Projects should appear"
echo ""
echo "4. Verify Live Preview Updates"
echo "   - Right panel should update automatically"
echo "   - Preview should show AI-generated content"
echo "   - Template should render correctly"
echo ""
echo "5. Verify No Auto-Save"
echo "   - Check browser network tab"
echo "   - Should see POST to /api/cvs/generate-preview/"
echo "   - Should NOT see POST to /api/cvs/"
echo "   - Database should NOT have new CV yet"
echo ""
echo "6. Edit Generated Content"
echo "   - Make changes to any field"
echo "   - Verify live preview updates"
echo "   - Changes should be reflected immediately"
echo ""
echo "7. Save CV"
echo "   - Click 'Save CV' button"
echo "   - Should see success message"
echo "   - Database should now have the CV"
echo "   - URL should update with CV ID"
echo ""
echo "8. Test Error Handling"
echo "   - Stop backend or disable GROQ_API_KEY"
echo "   - Click 'AI Generate'"
echo "   - Should see error alert"
echo "   - Form should remain editable"
echo ""
echo "Expected Results:"
echo "✓ AI generates content without auto-saving"
echo "✓ Form fields populate with generated data"
echo "✓ Live preview updates immediately"
echo "✓ User can review and edit before saving"
echo "✓ Explicit 'Save CV' click required"
echo "✓ Error handling shows appropriate messages"
echo ""
echo "API Endpoints:"
echo "- Preview: POST /api/cvs/generate-preview/ (new)"
echo "- Save: POST /api/cvs/ or PATCH /api/cvs/{id}/ (existing)"
echo ""
echo "==================================="

