# Generated by Django 4.2.26 on 2025-11-07 11:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="TrainerResult",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "module_key",
                    models.CharField(
                        choices=[
                            ("frontend-basics", "Frontend Basics"),
                            ("backend-basics", "Backend Basics"),
                            ("algorithms", "Algorithms"),
                            ("system-design", "System Design"),
                            ("behavioral", "Behavioral Questions"),
                        ],
                        db_index=True,
                        max_length=50,
                    ),
                ),
                ("attempts", models.IntegerField(default=1)),
                ("score", models.DecimalField(decimal_places=2, max_digits=5)),
                (
                    "max_score",
                    models.DecimalField(decimal_places=2, default=100, max_digits=5),
                ),
                ("metadata", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="trainer_results",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "trainer_results",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["user", "module_key", "-created_at"],
                        name="trainer_res_user_id_1aacab_idx",
                    )
                ],
            },
        ),
    ]
