# Generated by Django 5.2.8 on 2025-11-08 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interview', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='interviewsession',
            name='can_retake',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='interviewsession',
            name='detailed_review',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
