# Generated by Django 5.2.8 on 2025-11-08 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cv',
            name='template_key',
            field=models.CharField(choices=[('clean', 'Clean Template'), ('two-column', 'Two Column Template'), ('modern', 'Modern Template'), ('professional', 'Professional Template')], default='clean', max_length=50),
        ),
    ]
